import os
from building import * 

cwd = GetCurrentDir()

src  = []
inc  = []
inc  = inc + [cwd]

# add group to IDE project
objs = DefineGroup('lvgl', src, depend = ['RP_USING_LVGL'], CPPPATH = inc)
list = os.listdir(cwd)

if GetDepend('RP_USING_LVGL'):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
