from building import * 
import rtconfig

cwd = GetCurrentDir()

src = []
inc = []

inc = inc + [cwd]
inc = inc + [cwd + "/lv_core"]
inc = inc + [cwd + "/lv_draw"]
inc = inc + [cwd + "/lv_font"]
inc = inc + [cwd + "/lv_hal"]
inc = inc + [cwd + "/lv_misc"]
inc = inc + [cwd + "/lv_themes"]
inc = inc + [cwd + "/lv_widgets"]

src = src + Glob('./lv_core/*.c')
src = src + Glob('./lv_draw/*.c')
src = src + Glob('./lv_font/*.c')
src = src + Glob('./lv_hal/*.c')
src = src + Glob('./lv_misc/*.c')
src = src + Glob('./lv_themes/*.c')
src = src + Glob('./lv_widgets/*.c')

LOCAL_CCFLAGS = ''

if rtconfig.CROSS_TOOL == 'gcc':
    LOCAL_CCFLAGS += ' -std=c99'
elif rtconfig.CROSS_TOOL == 'keil':
    LOCAL_CCFLAGS += ' --c99 --gnu -g -W'

group = DefineGroup('lvgl', src, depend = ['RP_USING_LVGL'], CPPPATH = inc, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
